apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: nextjs
spec:
  securityContext:
    fsGroup: 1000  # Add this to ensure the group has the correct permissions
  containers:
  - name: jnlp
    image: "jenkins/inbound-agent:3248.v65ecb_254c298-2"
    volumeMounts:
    - mountPath: /home/jenkins/agent
      name: workspace-volume
      readOnly: false
    - name: docker-graph-storage
      mountPath: /var/lib/docker         
    env:
    - name: DOCKER_HOST
      value: "tcp://localhost:2375"
  - name: jenkins-agent
    image: docker:19.03.12-dind
    securityContext:
      privileged: true  # Necessary for Docker-in-Docker to work
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ""
    volumeMounts:
    - name: docker-graph-storage
      mountPath: /var/lib/docker
  volumes:
  - name: docker-graph-storage
    emptyDir: {}
  - name: workspace-volume
    emptyDir: {}
