apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: nextjs
spec:
  securityContext:
    fsGroup: 1000  # Add this to ensure the group has the correct permissions
  containers:
  - name: jnlp
    image: "jenkins/inbound-agent:3256.v88a_f6e922152-1"
    volumeMounts:
    - mountPath: /home/jenkins/agent
      name: workspace-volume
      readOnly: false
    - name: docker-graph-storage
      mountPath: /var/lib/docker         
    env:
    - name: DOCKER_HOST
      value: "tcp://localhost:2375"
  - name: nextjs
    image: public.ecr.aws/n3g1a9g4/custom-image:test-dockerv5   #bk:test-docker-1408-09
    securityContext:
      privileged: true  # Necessary for Docker-in-Docker to work
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ""
    command: ["tail", "-f", "/dev/null"]  # Keeps the container running for interaction
    volumeMounts:
    - name: workspace-volume
      mountPath: /workspace
    - name: docker-socket-volume
      mountPath: /var/run/docker.sock
    - name: docker-graph-storage
      mountPath: /var/lib/docker
    - name: jenkins-cache
      mountPath: /usr/local/share/.cache
  - name: docker
    image: public.ecr.aws/n3g1a9g4/custom-image:did-03
    securityContext:
      privileged: true
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ""
    volumeMounts:
    - name: docker-graph-storage
      mountPath: /var/lib/docker
    # resources:
    #   limits:
    #     cpu: 512m
    #     memory: 512Mi
    #   requests:
    #     cpu: 256m
    #     memory: 256Mi  
  # - name: docker
  #   image: docker:19.03.12-dind
  #   securityContext:
  #     privileged: true
  #   volumeMounts:
  #   - name: docker-graph-storage
  #     mountPath: /var/lib/docker
  volumes:
  - name: docker-graph-storage
    emptyDir: {}
  - name: workspace-volume
    emptyDir: {}
  - name: docker-socket-volume
    hostPath:
      path: /var/run/docker.sock
  - name: jenkins-cache
    persistentVolumeClaim:
      claimName: jenkins-cache
  #nodeSelector:
    #kubernetes.io/os: development
  #restartPolicy: Never 
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: instancePurpose
            operator: In
            values:
            - deployment  
