apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: nextjs
spec:
  securityContext:
    fsGroup: 1000  # Add this to ensure the group has the correct permissions
  containers:
  - name: nextjs
    image: public.ecr.aws/n3g1a9g4/custom-image:test-docker-7
    command: ["sh", "-c", "cat"]
    tty: true
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      readOnlyRootFilesystem: false
      allowPrivilegeEscalation: false
    volumeMounts:
    - mountPath: /home/jenkins/
      name: jenkins-cache
    - mountPath: /home/jenkins/agent
      name: workspace-volume
  - name: jnlp
    image: "jenkins/inbound-agent:3248.v65ecb_254c298-2"
    volumeMounts:
    - mountPath: /home/jenkins/agent
      name: workspace-volume
      readOnly: false
  - name: docker
    image: docker:19.03.12-dind
    securityContext:
      privileged: true
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ""
    volumeMounts:
    - name: docker-graph-storage
      mountPath: /var/lib/docker

  nodeSelector:
    instancePurpose: deployment
  restartPolicy: Never
  volumes:
  - name: jenkins-cache
    persistentVolumeClaim:
      claimName: jenkins-cache
  - emptyDir:
      medium: ""
    name: workspace-volume
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
  - name: docker-graph-storage
    emptyDir: {}
